name: ci
   
on:
  push:
    branches:
      - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and test
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: test
          load: true
      - name: Push to Docker Hub
        if: ${{ success() }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: prod
          tags: ${{ github.repository }}:${{ github.sha }}
